### ISSUE TITLE
while trying to update conflunce page , geting below mention error

### ISSUE THREAD

**Issue by shajainp** [AstroMatt/atlassian-python-api#18]
Traceback (most recent call last):
  File "con_update.py", line 37, in <module>
    parent_id=22028117
  File "C:\Python36-32\lib\site-packages\atlassian\confluence.py", line 76, in update_page
    'version': {'number': version}})
  File "C:\Python36-32\lib\site-packages\atlassian\__init__.py", line 57, in put
    return self.request('PUT', path=path, data=data, headers=headers).json()
  File "C:\Python36-32\lib\site-packages\atlassian\__init__.py", line 42, in request
    response.raise_for_status()
  File "C:\Python36-32\lib\site-packages\requests\models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error``

```
from pprint import pprint
from atlassian import Confluence

confluence = Confluence(
    url='xxx',
    username='xxx',
    password='xxx')


status = confluence.update_page(
    parent_id=22028117,
    page_id=38284221,
	title='',
    body='<h1 id="WindowsSignatureSet2.4.131.3-2-HandoffinstructionstoOperations">Handoff instructions to Operations</h1>',
	
 )

print(status)
```

**Comment by AstroMatt** [comment]
I think that confluence pages cannot be updated with empty title.
Please try with setting something

**Comment by shajainp** [comment]
thanks @AstroMatt 

one more help needed, how can pass body via file

**Comment by AstroMatt** [comment]
```
with open('index.html') as f:
    content = file.read()
```
then use `content` variable as body
