### ISSUE TITLE
user_deactivate not working

### ISSUE THREAD

**Issue by cjyar** [AstroMatt/atlassian-python-api#80]
I'm not able to get `user_deactivate` to work. I'm running this against a JIRA server version 7.3.1:

```python
from atlassian import Jira
import sys
import os

jira = Jira(
    url='https://jira.example.com',
    username=os.environ['JIRA_USERNAME'],
    password=os.environ['JIRA_PASSWORD'])

print(sys.argv[1])
jira.user_deactivate(sys.argv[1])
```

I'm getting back an enormous Java stack trace, wrapped in HTML. The most interesting part of the stack trace seems to be:
```
java.lang.NullPointerException
        at com.atlassian.jira.web.action.admin.user.EditUser.buildNewUser(EditUser.java:86) [classes/:?]
        at com.atlassian.jira.web.action.admin.user.EditUser.doValidation(EditUser.java:45) [classes/:?]
```

This JIRA server has been modified to work with Okta for SAML2 authentication, which involves disabling the `jsp.login_jsp` servlet. Is that the cause of the error I'm seeing?

**Comment by cjyar** [comment]
Thanks for the suggestion.
